// Export pages
export '/estudiante/public/inicio/inicio_widget.dart' show InicioWidget;
export '/estudiante/public/registro/registro_widget.dart' show RegistroWidget;
export '/estudiante/public/login/login_widget.dart' show LoginWidget;
export '/estudiante/housing/listado_housing/listado_housing_widget.dart'
    show ListadoHousingWidget;
export '/estudiante/mi_perfil_estudiante/mi_perfil_estudiante_widget.dart'
    show MiPerfilEstudianteWidget;
export '/estudiante/reservaexitosa/reservaexitosa_widget.dart'
    show ReservaexitosaWidget;
export '/estudiante/housing/housign/housign_widget.dart' show HousignWidget;
export '/estudiante/policy/politicasde_reembolso/politicasde_reembolso_widget.dart'
    show PoliticasdeReembolsoWidget;
export '/estudiante/policy/nosotros/nosotros_widget.dart' show NosotrosWidget;
export '/estudiante/policy/terminosycondiciones/terminosycondiciones_widget.dart'
    show TerminosycondicionesWidget;
export '/estudiante/events/crear_evento/crear_evento_widget.dart'
    show CrearEventoWidget;
export '/estudiante/events/evento/evento_widget.dart' show EventoWidget;
export '/estudiante/events/listar_eventos/listar_eventos_widget.dart'
    show ListarEventosWidget;
export '/estudiante/reservas/reservas_widget.dart' show ReservasWidget;
export '/estudiante/admin/validarqr/scaneo_exitoso/scaneo_exitoso_widget.dart'
    show ScaneoExitosoWidget;
export '/estudiante/admin/validarqr/scaneo_error/scaneo_error_widget.dart'
    show ScaneoErrorWidget;
export '/estudiante/events/editar_evento/editar_evento_widget.dart'
    show EditarEventoWidget;
export '/estudiante/booking/reserva_id/reserva_id_widget.dart'
    show ReservaIdWidget;
export '/estudiante/policy/faq/faq_widget.dart' show FaqWidget;
export '/password_recovery/recuperar_contrasena/recuperar_contrasena_widget.dart'
    show RecuperarContrasenaWidget;
export '/password_recovery/codigo_enviado/codigo_enviado_widget.dart'
    show CodigoEnviadoWidget;
export '/password_recovery/codigo_de_validacion/codigo_de_validacion_widget.dart'
    show CodigoDeValidacionWidget;
export '/password_recovery/new_password/new_password_widget.dart'
    show NewPasswordWidget;
export '/estudiante/planes_de_membresia/planes_de_membresia_widget.dart'
    show PlanesDeMembresiaWidget;
export '/estudiante/planes/detalles_de_plan_basic/detalles_de_plan_basic_widget.dart'
    show DetallesDePlanBasicWidget;
export '/estudiante/listar_servicios/listar_servicios_widget.dart'
    show ListarServiciosWidget;
export '/comercio/home_comercio/home_comercio_widget.dart'
    show HomeComercioWidget;
export '/comercio/estadisticas/estadisticas_widget.dart'
    show EstadisticasWidget;
export '/comercio/stat_profile_views/stat_profile_views_widget.dart'
    show StatProfileViewsWidget;
export '/admin/home_admin/home_admin_widget.dart' show HomeAdminWidget;
export '/comercio/establecer_contrasena/establecer_contrasena_widget.dart'
    show EstablecerContrasenaWidget;
export '/estudiante/services/servicio/servicio_widget.dart' show ServicioWidget;
export '/admin/servicios/crear_servicio/crear_servicio_widget.dart'
    show CrearServicioWidget;
export '/admin/servicios/crear_categoria_servicio/crear_categoria_servicio_widget.dart'
    show CrearCategoriaServicioWidget;
export '/admin/descuentos/crear_descuento/crear_descuento_widget.dart'
    show CrearDescuentoWidget;
export '/admin/descuentos/crear_editar_categoria_descuento/crear_editar_categoria_descuento_widget.dart'
    show CrearEditarCategoriaDescuentoWidget;
export '/estudiante/discoint/descuentos/descuentos_widget.dart'
    show DescuentosWidget;
export '/estudiante/services/services_by_category/services_by_category_widget.dart'
    show ServicesByCategoryWidget;
export '/admin/servicios/editar_servicio/editar_servicio_widget.dart'
    show EditarServicioWidget;
export '/admin/servicios/editar_categoria_servicio/editar_categoria_servicio_widget.dart'
    show EditarCategoriaServicioWidget;
export '/admin/descuentos/editar_descuento/editar_descuento_widget.dart'
    show EditarDescuentoWidget;
export '/estudiante/planes/detalles_plan/detalles_plan_widget.dart'
    show DetallesPlanWidget;
export '/estudiante/paymen_succces/paymen_succces_widget.dart'
    show PaymenSucccesWidget;
export '/estudiante/planes/detalle_mi_plan/detalle_mi_plan_widget.dart'
    show DetalleMiPlanWidget;
export '/admin/housign_admin/create_housing/create_housing_widget.dart'
    show CreateHousingWidget;
export '/admin/users/crear_comercio/crear_comercio_widget.dart'
    show CrearComercioWidget;
export '/comercio/stat_local_views/stat_local_views_widget.dart'
    show StatLocalViewsWidget;
export '/comercio/stat_eventos_comercio/stat_eventos_comercio_widget.dart'
    show StatEventosComercioWidget;
export '/comercio/editar_perfil_comercio/editar_perfil_comercio_widget.dart'
    show EditarPerfilComercioWidget;
export '/admin/eventos_admin/categoria_eventos/categoria_eventos_widget.dart'
    show CategoriaEventosWidget;
export '/admin/eventos_admin/crear_categoria_e/crear_categoria_e_widget.dart'
    show CrearCategoriaEWidget;
export '/admin/eventos_admin/editar_categoria_e/editar_categoria_e_widget.dart'
    show EditarCategoriaEWidget;
export '/admin/transaction_details/transaction_details_widget.dart'
    show TransactionDetailsWidget;
export '/tickets/seleccionar_accion_tickets/seleccionar_accion_tickets_widget.dart'
    show SeleccionarAccionTicketsWidget;
export '/tickets/crear_un_ticket/crear_un_ticket_widget.dart'
    show CrearUnTicketWidget;
export '/tickets/lista_tickets/lista_tickets_widget.dart'
    show ListaTicketsWidget;
export '/admin/users/seleccionar_tipo_usuario/seleccionar_tipo_usuario_widget.dart'
    show SeleccionarTipoUsuarioWidget;
export '/admin/users/perfil_estudiante_by_id/perfil_estudiante_by_id_widget.dart'
    show PerfilEstudianteByIdWidget;
export '/estudiante/perfil/editar_perfil_user/editar_perfil_user_widget.dart'
    show EditarPerfilUserWidget;
export '/chat/listado_chats/listado_chats_widget.dart' show ListadoChatsWidget;
export '/admin/f_a_qadmin/listado_f_a_q/listado_f_a_q_widget.dart'
    show ListadoFAQWidget;
export '/admin/eventos_admin/reservas_admin/reservas_admin_widget.dart'
    show ReservasAdminWidget;
export '/estudiante/admin/validarqr/detalle_reserva/detalle_reserva_widget.dart'
    show DetalleReservaWidget;
export '/admin/servicios/seleccionar_accion_servicio/seleccionar_accion_servicio_widget.dart'
    show SeleccionarAccionServicioWidget;
export '/admin/transacciones/listado_transacciones/listado_transacciones_widget.dart'
    show ListadoTransaccionesWidget;
export '/admin/housign_admin/lista_housing_admin/lista_housing_admin_widget.dart'
    show ListaHousingAdminWidget;
export '/admin/housign_admin/editar_housing/editar_housing_widget.dart'
    show EditarHousingWidget;
export '/admin/listar_eventos_admin/listar_eventos_admin_widget.dart'
    show ListarEventosAdminWidget;
export '/admin/users/lista_usuario_comercios/lista_usuario_comercios_widget.dart'
    show ListaUsuarioComerciosWidget;
export '/admin/descuentos/seleccionar_accion_descuentos/seleccionar_accion_descuentos_widget.dart'
    show SeleccionarAccionDescuentosWidget;
export '/admin/descuentos/lista_descuentos_admin/lista_descuentos_admin_widget.dart'
    show ListaDescuentosAdminWidget;
export '/admin/users/perfil_comercio_by_id/perfil_comercio_by_id_widget.dart'
    show PerfilComercioByIdWidget;
export '/page_init/page_init_widget.dart' show PageInitWidget;
export '/chat/chat_id/chat_id_widget.dart' show ChatIdWidget;
export '/admin/users/lista_usuario_estudiantes/lista_usuario_estudiantes_widget.dart'
    show ListaUsuarioEstudiantesWidget;
export '/admin/users/crear_estudiante/crear_estudiante_widget.dart'
    show CrearEstudianteWidget;
export '/comercio/editar_perfil_comercio_admin/editar_perfil_comercio_admin_widget.dart'
    show EditarPerfilComercioAdminWidget;
export '/comercio/mi_perfil_comercio/mi_perfil_comercio_widget.dart'
    show MiPerfilComercioWidget;
export '/estudiante/perfil/editar_perfil_user_admin/editar_perfil_user_admin_widget.dart'
    show EditarPerfilUserAdminWidget;
export '/admin/eventos_admin/listar_servicios_admin/listar_servicios_admin_widget.dart'
    show ListarServiciosAdminWidget;
export '/admin/eventos_admin/listar_categorias_servicios_admin/listar_categorias_servicios_admin_widget.dart'
    show ListarCategoriasServiciosAdminWidget;
export '/estudiante/discoint/detalles_de_descuento/detalles_de_descuento_widget.dart'
    show DetallesDeDescuentoWidget;
export '/admin/descuentos/lista_categoria_descuentos_admin/lista_categoria_descuentos_admin_widget.dart'
    show ListaCategoriaDescuentosAdminWidget;
export '/admin/f_a_qadmin/crear_editar_f_a_q/crear_editar_f_a_q_widget.dart'
    show CrearEditarFAQWidget;
export '/admin/f_a_qadmin/listar_f_a_q_admin/listar_f_a_q_admin_widget.dart'
    show ListarFAQAdminWidget;
export '/admin/f_a_qadmin/listado_f_a_q_copy/listado_f_a_q_copy_widget.dart'
    show ListadoFAQCopyWidget;
export '/estudiante/perfil/editar_perfil_user_primer_loguin/editar_perfil_user_primer_loguin_widget.dart'
    show EditarPerfilUserPrimerLoguinWidget;
export '/estudiante/perfil/editar_perfil_comercio_primer_loguin/editar_perfil_comercio_primer_loguin_widget.dart'
    show EditarPerfilComercioPrimerLoguinWidget;
export '/password_recovery/recuperar_contrasena_copy/recuperar_contrasena_copy_widget.dart'
    show RecuperarContrasenaCopyWidget;
